-- Phase-one schema, retained so an unversioned phase-one database can be upgraded by 0002.
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS math_imports (id TEXT PRIMARY KEY, user_id TEXT, source_type TEXT NOT NULL, source_file_path TEXT NOT NULL, status TEXT NOT NULL, page_count INTEGER NOT NULL DEFAULT 0, error_code TEXT, error_message TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS math_pages (id TEXT PRIMARY KEY, import_id TEXT NOT NULL REFERENCES math_imports(id), page_index INTEGER NOT NULL, original_image_path TEXT NOT NULL, normalized_image_path TEXT, print_view_path TEXT, handwriting_view_path TEXT, handwriting_mask_path TEXT, width INTEGER, height INTEGER, transform_metadata TEXT NOT NULL, segmentation_status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS math_raw_parse_results (id TEXT PRIMARY KEY, page_id TEXT NOT NULL REFERENCES math_pages(id), provider TEXT NOT NULL, pipeline TEXT NOT NULL, provider_version TEXT, raw_json_path TEXT NOT NULL, raw_summary TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS math_regions (id TEXT PRIMARY KEY, page_id TEXT NOT NULL REFERENCES math_pages(id), region_type TEXT NOT NULL, bbox TEXT NOT NULL, polygon TEXT NOT NULL, crop_path TEXT, source_view TEXT NOT NULL, reading_order INTEGER NOT NULL, layout_score REAL, classification_score REAL, occluded_by_handwriting INTEGER NOT NULL DEFAULT 0, requires_review INTEGER NOT NULL DEFAULT 0, review_reasons TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS math_source_blocks (id TEXT PRIMARY KEY, page_id TEXT NOT NULL REFERENCES math_pages(id), parent_region_id TEXT REFERENCES math_regions(id), block_type TEXT NOT NULL, bbox TEXT NOT NULL, crop_path TEXT, source_type TEXT NOT NULL, reading_order INTEGER NOT NULL, previous_block_id TEXT, next_block_id TEXT, requires_review INTEGER NOT NULL DEFAULT 0, review_reasons TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS math_formula_candidates (id TEXT PRIMARY KEY, page_id TEXT NOT NULL REFERENCES math_pages(id), region_id TEXT REFERENCES math_regions(id), source_block_id TEXT REFERENCES math_source_blocks(id), bbox TEXT NOT NULL, polygon TEXT NOT NULL, crop_path TEXT, source_type TEXT NOT NULL, role TEXT NOT NULL, raw_latex TEXT, normalized_latex TEXT, user_confirmed_latex TEXT, layout_score REAL, recognition_score REAL, recognition_score_type TEXT, parseable INTEGER, occluded_by_handwriting INTEGER NOT NULL DEFAULT 0, requires_review INTEGER NOT NULL DEFAULT 0, review_reasons TEXT NOT NULL, reading_order INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS math_formula_revisions (id TEXT PRIMARY KEY, formula_id TEXT NOT NULL REFERENCES math_formula_candidates(id), field_name TEXT NOT NULL, before_value TEXT, after_value TEXT, edited_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS math_problems (id TEXT PRIMARY KEY, import_id TEXT NOT NULL REFERENCES math_imports(id), page_id TEXT NOT NULL REFERENCES math_pages(id), problem_bbox TEXT NOT NULL, problem_crop_path TEXT, recognition_status TEXT NOT NULL, parse_status TEXT NOT NULL, solve_status TEXT NOT NULL, verification_status TEXT NOT NULL, problem_type TEXT, requires_review INTEGER NOT NULL DEFAULT 0, review_reasons TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
