PRAGMA foreign_keys = ON;
ALTER TABLE math_imports ADD COLUMN source_sha256 TEXT;
ALTER TABLE math_imports ADD COLUMN source_size_bytes INTEGER;
ALTER TABLE math_imports ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE math_pages ADD COLUMN updated_at TEXT;
ALTER TABLE math_pages ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE math_regions ADD COLUMN created_at TEXT;
ALTER TABLE math_regions ADD COLUMN updated_at TEXT;
ALTER TABLE math_regions ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE math_source_blocks ADD COLUMN created_at TEXT;
ALTER TABLE math_source_blocks ADD COLUMN updated_at TEXT;
ALTER TABLE math_source_blocks ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE math_formula_revisions ADD COLUMN source_revision INTEGER;
ALTER TABLE math_problems ADD COLUMN user_id TEXT;
ALTER TABLE math_problems ADD COLUMN source_revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE math_problems ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE math_problems ADD COLUMN expected_revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE math_problems ADD COLUMN problem_type_hint TEXT;
ALTER TABLE math_problems ADD COLUMN variable_domains_json TEXT NOT NULL DEFAULT '{}';
UPDATE math_imports SET user_id=COALESCE(user_id, 'legacy'), revision=COALESCE(revision,1);
UPDATE math_pages SET updated_at=COALESCE(updated_at,created_at), revision=COALESCE(revision,1);
UPDATE math_regions SET created_at=COALESCE(created_at,(SELECT created_at FROM math_pages p WHERE p.id=math_regions.page_id)), updated_at=COALESCE(updated_at,(SELECT created_at FROM math_pages p WHERE p.id=math_regions.page_id));
UPDATE math_source_blocks SET created_at=COALESCE(created_at,(SELECT created_at FROM math_pages p WHERE p.id=math_source_blocks.page_id)), updated_at=COALESCE(updated_at,(SELECT created_at FROM math_pages p WHERE p.id=math_source_blocks.page_id));
UPDATE math_problems SET user_id=COALESCE(user_id,(SELECT user_id FROM math_imports i WHERE i.id=math_problems.import_id),'legacy'), problem_type_hint=COALESCE(problem_type_hint,problem_type), expected_revision=COALESCE(expected_revision,revision,1);
CREATE TABLE IF NOT EXISTS math_problem_sources (id TEXT PRIMARY KEY, problem_id TEXT NOT NULL REFERENCES math_problems(id), source_kind TEXT NOT NULL CHECK(source_kind IN ('formula','source_block','region')), source_id TEXT NOT NULL, semantic_role TEXT NOT NULL CHECK(semantic_role IN ('prompt','condition','user_step','user_answer')), reading_order INTEGER NOT NULL, created_at TEXT NOT NULL, UNIQUE(problem_id,source_kind,source_id));
CREATE TABLE IF NOT EXISTS math_processing_jobs (id TEXT PRIMARY KEY, resource_type TEXT NOT NULL, resource_id TEXT NOT NULL, job_type TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('queued','claimed','completed','failed')), attempt_count INTEGER NOT NULL DEFAULT 0, claimed_by TEXT, claimed_at TEXT, lease_expires_at TEXT, available_at TEXT NOT NULL, last_error_code TEXT, last_error_message TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS math_idempotency_records (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, operation_type TEXT NOT NULL, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL, status TEXT NOT NULL, response_status INTEGER, resource_type TEXT, resource_id TEXT, response_body TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, expires_at TEXT, UNIQUE(user_id,operation_type,idempotency_key));
CREATE TABLE IF NOT EXISTS math_parse_results (id TEXT PRIMARY KEY, problem_id TEXT NOT NULL REFERENCES math_problems(id), input_source_revision INTEGER NOT NULL, input_hash TEXT NOT NULL, parser_version TEXT NOT NULL, status TEXT NOT NULL, ast_json TEXT, problem_ir_json TEXT, created_at TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, UNIQUE(problem_id,input_source_revision,input_hash,parser_version));
CREATE TABLE IF NOT EXISTS math_solve_results (id TEXT PRIMARY KEY, problem_id TEXT NOT NULL REFERENCES math_problems(id), parse_result_id TEXT NOT NULL REFERENCES math_parse_results(id), input_parse_hash TEXT NOT NULL, solver_version TEXT NOT NULL, status TEXT NOT NULL, result_json TEXT, created_at TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, UNIQUE(problem_id,parse_result_id,input_parse_hash,solver_version));
CREATE TABLE IF NOT EXISTS math_verification_reports (id TEXT PRIMARY KEY, problem_id TEXT NOT NULL REFERENCES math_problems(id), solve_result_id TEXT NOT NULL REFERENCES math_solve_results(id), input_solve_hash TEXT NOT NULL, verifier_version TEXT NOT NULL, status TEXT NOT NULL, report_json TEXT, created_at TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, UNIQUE(problem_id,solve_result_id,input_solve_hash,verifier_version));
CREATE UNIQUE INDEX IF NOT EXISTS idx_math_pages_import_order ON math_pages(import_id,page_index);
CREATE INDEX IF NOT EXISTS idx_math_imports_user ON math_imports(user_id);
CREATE INDEX IF NOT EXISTS idx_math_formula_page_order ON math_formula_candidates(page_id,reading_order);
CREATE INDEX IF NOT EXISTS idx_math_problem_user ON math_problems(user_id,updated_at);
CREATE INDEX IF NOT EXISTS idx_math_problem_sources_problem ON math_problem_sources(problem_id,reading_order);
CREATE INDEX IF NOT EXISTS idx_math_jobs_claimable ON math_processing_jobs(status,available_at,lease_expires_at);
